name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Install tools
      run: |
        sudo apt-get -y install rubygems ruby-dev zlib1g-dev

    - name: Build Site
      run: |
        export GEM_HOME=$HOME/.gem
        export PATH=$PATH:$GEM_HOME/bin
        username=`git log -1 --pretty=format:'%an'`
        email=`git log -1 --pretty=format:'%ae'`
        git config --global user.name $username
        git config --global user.email $email
        ./publish.sh

    - name: Publish Site
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        git push origin asf-site:asf-site
