name: CI

on:
  repository_dispatch:
    types: docs
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Checkout NuttX Documentation
      uses: actions/checkout@v2
      with:
        repository: apache/incubator-nuttx
        fetch-depth: 1
        ref: master
        path: nuttx/master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Generate requirements.txt file
      run: |
        cd nuttx/master/Documentation/
        pip3 install pipenv
        pipenv lock -r > requirements.txt
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "nuttx/master/Documentation/"

    - name: Install tools
      run: |
        sudo apt-get -y install rubygems ruby-dev zlib1g-dev

    - name: Build Site
      run: |
        export GEM_HOME=$HOME/.gem
        export PATH=$PATH:$GEM_HOME/bin
        username=`git log -1 --pretty=format:'%an'`
        email=`git log -1 --pretty=format:'%ae'`
        git config --global user.name $username
        git config --global user.email $email
        ./publish.sh

    - name: Upload artifact of staged site
      uses: actions/upload-artifact@v2
      with:
        name: static-site
        path: content

    - name: Publish Site
      if: (github.event_name == 'push' || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch' ) && github.ref == 'refs/heads/master'
      run: |
        git push origin asf-site:asf-site
